=== TomDolidon/Course-XML/presentation.xsd
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:xs="urn:presentation"
        targetNamespace="urn:presentation"
        elementFormDefault="qualified"

>

    <!-- racine -->
    <element name="présentation" type="xs:type_presentation" />

    <complexType name="type_presentation">
        <sequence>
            <element name="en-tête" >
                <complexType>
                    <sequence>
                        <element name="modèle" maxOccurs="unbounded">
                            <complexType>
                                <attribute  name="nom"  type="string" use="required"/>
                                <attribute name="color" type="string" use="required"/>
                                <attribute name="taille" type="integer" use="optional"/>
                            </complexType>
                        </element>
                    </sequence>
                </complexType>
                <unique name="uniqueName">
                    <selector xpath="xs:modèle"/>
                    <field xpath="@nom"/>
                </unique>
            </element>
            <element name="diapo" type="xs:type_diapo" maxOccurs="unbounded"/>
        </sequence>
    </complexType>

    <complexType name="type_diapo">
        <sequence>
            <element name="titre" type="string"/>
            <element name="corps" type="xs:type_corps"/>
        </sequence>
        <attribute name="ref_modèle" type="string" use="required"/>
    </complexType>

    <complexType name="type_corps">
        <sequence maxOccurs="unbounded" minOccurs="0">
            <element name="bloc" type="xs:type_bloc"/>
        </sequence>
    </complexType>

    <complexType name="type_bloc">
        <choice>
            <element name="para" type="xs:type_paragraphe"/>
            <element name="liste" type="xs:type_liste"/>
            <element name="image" type="xs:type_image"/>
        </choice>
    </complexType>

    <complexType name="type_paragraphe" mixed="true">
        <sequence maxOccurs="unbounded">
            <element name="gras" type="xs:type_gras" maxOccurs="unbounded" minOccurs="0"/>
            <element name="italique" type="xs:type_italique" maxOccurs="unbounded" minOccurs="0"/>
            <element name="couleur" type="xs:type_couleur" maxOccurs="unbounded" minOccurs="0"/>
        </sequence>
    </complexType>

    <complexType name="type_gras" mixed="true">
        <sequence maxOccurs="unbounded" minOccurs="0">
            <element name="gras" type="xs:type_gras" maxOccurs="unbounded" minOccurs="0"/>
            <element name="italique" type="xs:type_italique" maxOccurs="unbounded" minOccurs="0"/>
            <element name="couleur" type="xs:type_couleur" maxOccurs="unbounded" minOccurs="0"/>
        </sequence>
    </complexType>

    <complexType name="type_italique" mixed="true">
        <sequence maxOccurs="unbounded" minOccurs="0">
            <element name="gras" type="xs:type_gras" maxOccurs="unbounded" minOccurs="0"/>
            <element name="italique" type="xs:type_italique" maxOccurs="unbounded" minOccurs="0"/>
            <element name="couleur" type="xs:type_couleur" maxOccurs="unbounded" minOccurs="0"/>
        </sequence>
    </complexType>

    <complexType name="type_couleur" mixed="true">
        <sequence maxOccurs="unbounded" minOccurs="0">
            <element name="gras" type="xs:type_gras" maxOccurs="unbounded" minOccurs="0"/>
            <element name="italique" type="xs:type_italique" maxOccurs="unbounded" minOccurs="0"/>
            <element name="couleur" type="xs:type_couleur" maxOccurs="unbounded" minOccurs="0"/>
        </sequence>
    </complexType>

    <complexType name="type_liste">
        <sequence>
            <element name="item" type="xs:type_item" maxOccurs="unbounded"/>
        </sequence>
        <attribute name="type" type="string" use="optional"/>
    </complexType>

    <complexType name="type_item">
        <sequence>
            <element name="para" type="xs:type_paragraphe" maxOccurs="unbounded"/>
            <element name="liste" type="xs:type_liste" minOccurs="0"/>
        </sequence>
    </complexType>

    <complexType name="type_image">
        <attribute name="src" type="string" use="optional"/>
    </complexType>


</schema>

=== TomDolidon/Course-XML/presentation.xml
<?xml version="1.0" encoding="utf-8"?>

<!-- <!DOCTYPE présentation SYSTEM "presentation.dtd"> -->


<présentation
        xmlns="urn:presentation"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="urn:presentation presentation.xsd"
>

    <en-tête>
        <modèle nom="model1" color="FF00FF" taille="18" />
    </en-tête>

    <diapo ref_modèle="model1">

        <titre>Pourquoi Adil est-il si génial ? </titre>

        <corps>
            <bloc>
                <liste>
                    <item>
                        <para> Il est beau </para>
                    </item>
                    <item>
                        <para> <gras> Il est<italique>intelligent</italique> </gras>  </para>
                    </item>
                    <item>
                        <para> Il est humble </para>
                    </item>
                </liste>
            </bloc>

            <bloc>
                <image src="https://media-exp1.licdn.com/dms/image/C4E03AQHrsxq8BqmC9Q/profile-displayphoto-shrink_200_200/0?e=1586995200&amp;v=beta&amp;t=r6lvJFUfg2NWlTlDJn57dhTVWL_-AXBNWy2C2D3z4-A" />
            </bloc>

        </corps>
    </diapo>

</présentation>
